### ISSUE TITLE
Expose API for file tasks

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/nr-launcher#273]
Required API feature set:

### Folders
- Add Folder
- Rename Folder
- Move Folder
- Remove Folder
    - Considerations around limiting removal if contents present? 

### Files
- Add/Upload/Replace File
- Rename File
- Move File
- Remove File

**Comment by knolleary** [comment]
I've sketched out the API we'll use in the platform in #4357

The launcher API should use the same semantics - albeit with a different root path

- `GET /api/v1/projects/:instanceId/files/_/:path` - get directory listing - currently *not* for retrieving a file's contents
- `PUT /api/v1/projects/:instanceId/files/_/:path` - update file name (eg rename/move)
- `DELETE /api/v1/projects/:instanceId/files/_/:path` - delete file

The `share` options mentioned in #4357 at not required for the launcher - they will be handled by the platform.

I still need to specify how file upload will work - and again will need mirroring in the launcher.
